//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace GestionCommerciale.Models
{
    public partial class DECLARATIONS
    {
        public DECLARATIONS()
        {
            this.DECLARATIONS_EMPLOYEURS = new HashSet<DECLARATIONS_EMPLOYEURS>();
            this.DECLARATIONS_FACTURES = new HashSet<DECLARATIONS_FACTURES>();
            this.EMPLOYEES = new HashSet<EMPLOYEES>();
            this.GENERATIONS = new HashSet<GENERATIONS>();
            this.SAISIES = new HashSet<SAISIES>();
        }
        public string SOCIETE { get; set; }
        public string CODE { get; set; }
        public int ID { get; set; }
        public string MATRICULE { get; set; }
        public string ADRESSE { get; set; }
        public string BR { get; set; }
        public string CODE_EXPLOITATION { get; set; }
        public string ACTIVITE { get; set; }
        public string VILLE { get; set; }
        public string RUE { get; set; }
        public string NUMERO { get; set; }
        public string CODE_POSTAL { get; set; }
        public virtual ICollection<DECLARATIONS_EMPLOYEURS> DECLARATIONS_EMPLOYEURS { get; set; }
        public virtual ICollection<DECLARATIONS_FACTURES> DECLARATIONS_FACTURES { get; set; }
        public virtual ICollection<EMPLOYEES> EMPLOYEES { get; set; }
        public virtual ICollection<SAISIES> SAISIES { get; set; }
        public virtual ICollection<GENERATIONS> GENERATIONS { get; set; }

    }
    
}
