//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace GestionCommerciale.Models
{
    public partial class EMPLOYEES
    {
        public EMPLOYEES()
        {

            this.SAISIES = new HashSet<SAISIES>();
            this.ANNEXE_1 = new HashSet<ANNEXE_1>();
        }
    
        public int ID { get; set; }
        public string CIN { get; set; }
        public string FULLNAME { get; set; }
        public string NUM_ASS_SOC { get; set; }
        public Nullable<int> SOCIETE { get; set; }
        public Boolean ACTIF { get; set; }
        public string QUALIFICATION { get; set; }
        public string NUMERO { get; set; }
        public string ADRESSE { get; set; }
        public int SITUATION_FAMILIALE { get; set; }
        public int NOMBRE_ENFANT { get; set; }
        public string ACTIVITE { get; set; }
        [ForeignKey("SOCIETE")]
        public virtual DECLARATIONS SOCIETES { get; set; }
        public virtual ICollection<SAISIES> SAISIES { get; set; }
        public virtual ICollection<LIGNES_GENERATIONS> LIGNES_GENERATIONS { get; set; }
        public virtual ICollection<ANNEXE_1> ANNEXE_1 { get; set; }
        
    }
    
}
