//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GestionCommerciale.Models
{
    public partial class FACTURES_FOURNISSEURS
    {
        public FACTURES_FOURNISSEURS()
        {
            this.AVOIRS_FOURNISSEURS = new HashSet<AVOIRS_FOURNISSEURS>();
            this.LIGNES_FACTURES_FOURNISSEURS = new HashSet<LIGNES_FACTURES_FOURNISSEURS>();
        }
    
        public int ID { get; set; }
        public string CODE { get; set; }
        public System.DateTime DATE { get; set; }
        public string MODE_PAIEMENT { get; set; }
        public int FOURNISSEUR { get; set; }
        public decimal THT { get; set; }
        public decimal TTVA { get; set; }
        public decimal NHT { get; set; }
        public decimal TTC { get; set; }
        public decimal TNET { get; set; }
        public bool VALIDER { get; set; }
        public bool PAYEE { get; set; }
        public decimal REMISE { get; set; }
        public decimal TIMBRE { get; set; }
        public Nullable<int> COMMANDE_FOURNISSEUR { get; set; }
        public Nullable<int> BON_RECEPTION_FOURNISSEUR { get; set; }
    
        public virtual ICollection<AVOIRS_FOURNISSEURS> AVOIRS_FOURNISSEURS { get; set; }
        [ForeignKey("BON_RECEPTION_FOURNISSEUR")]
        public virtual BONS_RECEPTIONS_FOURNISSEURS BONS_RECEPTIONS_FOURNISSEURS { get; set; }
        [ForeignKey("COMMANDE_FOURNISSEUR")]
        public virtual COMMANDES_FOURNISSEURS COMMANDES_FOURNISSEURS { get; set; }
        [ForeignKey("FOURNISSEUR")]
        public virtual FOURNISSEURS FOURNISSEURS { get; set; }
        public virtual ICollection<LIGNES_FACTURES_FOURNISSEURS> LIGNES_FACTURES_FOURNISSEURS { get; set; }
    }
    
}
