//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GestionCommerciale.Models
{
    public partial class MOUVEMENETS_PRODUITS
    {
        public int ID { get; set; }
        public int PRODUIT { get; set; }
        public System.DateTime DATE_MOUVEMENT { get; set; }
        public string TYPE_MOUVEMENT { get; set; }
        public string CODE_MOUVEMENT { get; set; }
        public int QUANTITE_MOUVEMENT { get; set; }
        public int QUANTITE_AVANT_MOUVEMENT { get; set; }
        public int QUANTITE_APRES_MOUVEMENT { get; set; }
        [ForeignKey("PRODUIT")]
        public virtual PRODUITS PRODUITS { get; set; }
    }

}
