//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace GestionCommerciale.Models
{
    public partial class SAISIES
    {
        public SAISIES()
        {
        }
    
        public int ID { get; set; }
        public int MOIS { get; set; }
        public int ANNEE { get; set; }
        public int TRIMESTRE { get; set; }
        public Nullable<int> SOCIETE { get; set; }
        public Nullable<int> EMPLOYEE { get; set; }
        public double SALAIRE { get; set; }
        [ForeignKey("SOCIETE")]
        public virtual DECLARATIONS SOCIETES { get; set; }
        [ForeignKey("EMPLOYEE")]
        public virtual EMPLOYEES EMPLOYEES { get; set; }
        
    }
    
}
